apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtec-devops-task
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qtec-devops-task
  template:
    metadata:
      labels:
        app: qtec-devops-task
    spec:
      containers:
      - name: qtec-devops-task
        image: abrahimcse/qtec-devops-task:332ce4f
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
