apiVersion: apps/v1
kind: Deployment
metadata:
  name: qtec-devops-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qtec-devops-task
  template:
    metadata:
      labels:
        app: qtec-devops-task
    spec:
      containers:
      - name: qtec-devops-task
        image: abrahimcse/qtec-devops-task:170e8ec
        ports:
        - containerPort: 5000